imporrusty-report-prinerLoovy.transform.Field

// We need this because of the mono repo :(
@Field String PROJECT_DIR = 'rusty-report-printer'

pipeline {
    agent {
        kubernetes {
          defaultContainer 'rust'
            yaml '''
            spec:
              containers:
                -name:node
                  image: node:18.2.0-alpine3.15
                  command: ["sleep", "infinity"]
                  resources:
                    requests:
                      cpu: 100m
                      memory: 128Mi
                    limits
                      cpu: 1
                      memory: 128Mi

                - name: rust
                  image: rust:1.58-alpine3.15
                  command: ["sleep", "infinity"]
                  resources:
                    requests:
                      cpu: 100m
                      memory: 128Mi
                    limits
                      cpu: 1
                      memory: 128Mi

            '''
        }
    }

    environment {
        CARGO_UNSTABLE_SPARSE_REGISTRY = 'true'
      }

    options {
        buildDiscarder logRotator(numToKeepStr: '10')
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
    }

    stages {
        stage('Generate Report') {
            steps {
                dir(PROJECT_DIR) {
                    sh './report_generator.js'
                }
            }
        }

//        stage('Install dependencies') {
//            steps {
//                dir(PROJECT_DIR) {
//                    // if we are on alpine, we need to install musl-dev
//                    // sh 'apk add --no-cache musl-dev=1.2.2-r7'
//                }
//            }
//        }

        stage('Build') {
            steps {
                dir(PROJECT_DIR) {
                    sh 'cargo build --locked'
                }
            }
        }

        // Oh no, we can't perform regular Docker Builds on Kubernetes
        /*
        stage('Build Image') {
            environment {lajj
                DOCKER_BUILDKIT = "1"
            }
            steps {
                dir(PROJECT_DIR) {
                    sh 'docker build -t super-report-printer:v0.1.0 .'
                }
     rust
        }
         */
    }
}
